import type { LogLevel } from "spacetimedb";

export const CONFIG = {
  spacetime: {
    host: process.env.STDB_HOST ?? "https://maincloud.spacetimedb.com",
    databaseName: process.env.STDB_DB ?? "scrabblebot",
  },
  bot: {
    name: process.env.BOT_NAME ?? "bot",
    nonce: process.env.BOT_NONCE,
    tokenFilePrefix: ".token-",
  },
  sdk: {
    logLevel: "warn" as LogLevel,
  },
  dictionary: {
    minWordLength: 2,
    wordlistPathSegments: ["..", "..", "spacetimedb", "wordlist.txt"],
  },
  count: {
    none: 0,
    increment: 1,
  },
  collection: {
    emptyLength: 0,
  },
  process: {
    failureExitCode: 1,
  },
  credential: {
    claimResolveDelayMs: 1000,
  },
  finalWindow: {
    bagTotal: 2,
  },
  auction: {
    minBidLeadTimeMicros: 250_000n,
  },
  bidding: {
    noBidAmount: 0,
    noBidFloorExcludedLetters: ["Q"] as string[],
    fallbackLetterValue: 1,
    newLetterPremium: 2,
    minimumRepeatLetterBid: 1,
    minimumBalance: 0,
    letterValues: {
      A: 1,
      B: 3,
      C: 3,
      D: 2,
      E: 1,
      F: 4,
      G: 2,
      H: 4,
      I: 1,
      J: 8,
      K: 5,
      L: 1,
      M: 3,
      N: 1,
      O: 1,
      P: 3,
      Q: 10,
      R: 1,
      S: 1,
      T: 1,
      U: 1,
      V: 4,
      W: 4,
      X: 8,
      Y: 4,
      Z: 10,
    } as Record<string, number>,
  },
  scoring: {
    threeLetterMaxLength: 3,
    fourLetterLength: 4,
    fiveLetterLength: 5,
    sixLetterLength: 6,
    fourLetterNumerator: 3,
    fourLetterDenominator: 2,
    fiveLetterMultiplier: 2,
    sixLetterNumerator: 5,
    sixLetterDenominator: 2,
    sevenPlusMultiplier: 3,
  },
  live: {
    phaseNames: {
      beginning: "beginning",
      middle: "middle",
      end: "end",
    },
    testBalance: 100,
    fallbackLetterStrength: 1,
    noRackGain: 0,
    letterStrengths: {
      A: 3.8,
      B: 4.2,
      C: 7.6,
      D: 5.0,
      E: 3.6,
      F: 5.1,
      G: 5.0,
      H: 7.8,
      I: 3.7,
      J: 6.9,
      K: 8.2,
      L: 4.4,
      M: 5.0,
      N: 4.2,
      O: 3.6,
      P: 5.0,
      Q: 4.9,
      R: 4.5,
      S: 6.2,
      T: 4.4,
      U: 3.0,
      V: 3.8,
      W: 5.2,
      X: 8.8,
      Y: 7.2,
      Z: 12.8,
    } as Record<string, number>,
    phases: {
      beginning: {
        maxRound: 25,
        usualLetterWeight: 1,
        rackFitWeight: 0.25,
        bidMultiplier: 1.65,
        maxBidBalanceFraction: 0.3,
        reserveBalance: 45,
        minBid: 1,
      },
      middle: {
        maxRound: 60,
        usualLetterWeight: 0.35,
        rackFitWeight: 1.2,
        bidMultiplier: 2,
        maxBidBalanceFraction: 0.45,
        reserveBalance: 12,
        minBid: 1,
      },
      end: {
        maxRound: 98,
        usualLetterWeight: 0,
        rackFitWeight: 1,
        bidMultiplier: 2.2,
        maxBidBalanceFraction: 1,
        reserveBalance: 0,
        minBid: 1,
      },
    },
    finalThreeBagTotal: 2,
    wordPolicy: {
      finalDumpOnly: true,
      emergencyCashInEnabled: true,
      targetScore: 100,
      cashInMinScore: 32,
      catchUpBagTotal: 45,
      catchUpMinScore: 32,
      lateCatchUpBagTotal: 20,
      lateCatchUpMinScore: 28,
      emergencyBalance: 15,
      emergencyMinScore: 24,
      cashInDelayMs: 75,
    },
    valuation: {
      faceValueWeight: 0.25,
      vickreyBaselineBid: 10,
      qWithoutUGainThreshold: 8,
      qUSynergyValue: 12,
      smallRackMaxSize: 3,
      smallRackShift: 0.2,
      largeRackMinSize: 5,
      largeRackShift: 0.2,
      runtimeRackFitMaxRackSize: 12,
      firstPriceShade: 0.7,
    },
    bankrollPressure: {
      startRound: 1,
      endRound: 98,
      startBalance: 100,
      endBalance: 0,
      fullPressureBalanceDelta: 50,
      neutralMultiplier: 1,
      maxMultiplier: 1.2,
      minMultiplier: 0.8,
    },
  },
  professor: {
    enabledBotName: "the-professor",
    tableDirName: "professor",
    oneVOneTableFile: "one_v_one_livecommon.json",
    sixTableFile: "six_livecommon.json",
    minVisits: 20,
    oneVOneMinImprovement: 0.18,
    oneVOneMaxVariance: 0.06,
    oneVOneMaxBidDelta: 2,
    sixMinImprovement: 0.24,
    sixMaxVariance: 0.04,
    sixMaxBidDelta: 1,
    maxOverrideBalanceFraction: 0.35,
    lowBalanceFraction: 0.55,
    defaultPlayerCount: 2,
    multiplayerMinPlayers: 3,
    liveCommonRackCuts: [6, 10, 15],
    liveCommonVowelCuts: [1, 3],
    liveCommonBestRewardCuts: [0, 24, 36],
    balanceCuts: [10, 25, 45, 70, 100],
  },
  precompute: {
    outputDirSegments: ["src", "precomputed"],
    letterPriorFileName: "letter_prior.json",
    bestWordDirName: "best_word",
    tileGainDirName: "tile_gain",
    maxBestWordTableBytes: 8 * 1024 * 1024,
    sizeFilePrefix: "size-",
    jsonFileExtension: ".json",
    quietFlag: "--quiet",
    maxRackLetters: 8,
    letterPriorRackSize: 5,
    progressInterval: 100000,
    sampleOutputCount: 12,
    priorPrecisionFactor: 10,
    gainEncodingBase: 36,
    gainEncodingWidth: 2,
    jsonIndent: 2,
    letters: [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H",
      "I",
      "J",
      "K",
      "L",
      "M",
      "N",
      "O",
      "P",
      "Q",
      "R",
      "S",
      "T",
      "U",
      "V",
      "W",
      "X",
      "Y",
      "Z",
    ],
  },
  neat: {
    machine: {
      defaultWorkers: 24,
      minimumWorkers: 1,
      maximumDefaultWorkers: 28,
      cpuReserve: 4,
    },
    defaults: {
      mode: "evolve",
      matches: 200,
      generations: 60,
      population: 96,
      workers: 24,
      seed: 20260606,
      outFile: "tuned-config.json",
      generationDir: "tuned-generations",
      playerCount: 6,
      auctionType: "Vickrey",
      opponentProfile: "mixed",
    },
    cli: {
      base: 10,
      nextArgOffset: 1,
      modeFlag: "--mode",
      matchesFlag: "--matches",
      generationsFlag: "--generations",
      populationFlag: "--population",
      workersFlag: "--workers",
      seedFlag: "--seed",
      outFlag: "--out",
      generationDirFlag: "--generation-dir",
      playersFlag: "--players",
      auctionFlag: "--auction",
      opponentsFlag: "--opponents",
      compareAFlag: "--a",
      compareBFlag: "--b",
    },
    modes: {
      grid: "grid",
      evolve: "evolve",
      compare: "compare",
    },
    game: {
      totalTiles: 98,
      startingRackSize: 5,
      startingBalance: 100,
      auctionReserve: 1,
      defaultPlayerCount: 6,
      noFinalAuctionValue: 0,
      maxWholeBalanceFraction: 1,
      startingBag: {
        A: 9,
        B: 2,
        C: 2,
        D: 4,
        E: 12,
        F: 2,
        G: 3,
        H: 2,
        I: 9,
        J: 1,
        K: 1,
        L: 4,
        M: 2,
        N: 6,
        O: 8,
        P: 2,
        Q: 1,
        R: 6,
        S: 4,
        T: 6,
        U: 4,
        V: 2,
        W: 2,
        X: 1,
        Y: 2,
        Z: 1,
      } as Record<string, number>,
    },
    scoring: {
      threeLetterMaxLength: 3,
      fourLetterLength: 4,
      fiveLetterLength: 5,
      sixLetterLength: 6,
      fourLetterNumerator: 3,
      fourLetterDenominator: 2,
      fiveLetterMultiplier: 2,
      sixLetterNumerator: 5,
      sixLetterDenominator: 2,
      sevenPlusMultiplier: 3,
    },
    tunable: {
      bidMultiplier: 1.4,
      firstPriceShade: 0.65,
      maxBidBalanceFraction: 0.35,
      reserveBalance: 12,
      cashInMinScore: 34,
      finalDump: true,
      minBid: 1,
      endgameMultiplier: 2.5,
      finalAuctionMultiplier: 0,
      qPenalty: 0.55,
      synergyMultiplier: 1.25,
    },
    profiles: {
      liveStrategyName: "repo-live-phase",
      defaultStrategyName: "repo-neat-default",
      candidateStrategyName: "candidate",
      generated: [
        {
          name: "generated-conservative-bankroll",
          config: {
            bidMultiplier: 0.8,
            firstPriceShade: 0.55,
            maxBidBalanceFraction: 0.16,
            reserveBalance: 38,
            cashInMinScore: 24,
            finalDump: true,
            minBid: 1,
            endgameMultiplier: 1.4,
            finalAuctionMultiplier: 0,
            qPenalty: 0.35,
            synergyMultiplier: 1.05,
          },
        },
        {
          name: "generated-aggressive-tempo",
          config: {
            bidMultiplier: 2.25,
            firstPriceShade: 0.78,
            maxBidBalanceFraction: 0.68,
            reserveBalance: 4,
            cashInMinScore: 52,
            finalDump: true,
            minBid: 2,
            endgameMultiplier: 2.8,
            finalAuctionMultiplier: 0,
            qPenalty: 0.65,
            synergyMultiplier: 1.35,
          },
        },
        {
          name: "generated-endgame-surge",
          config: {
            bidMultiplier: 1.15,
            firstPriceShade: 0.62,
            maxBidBalanceFraction: 0.42,
            reserveBalance: 18,
            cashInMinScore: 40,
            finalDump: true,
            minBid: 1,
            endgameMultiplier: 5.4,
            finalAuctionMultiplier: 0.02,
            qPenalty: 0.5,
            synergyMultiplier: 1.2,
          },
        },
        {
          name: "generated-synergy-hunter",
          config: {
            bidMultiplier: 1.55,
            firstPriceShade: 0.7,
            maxBidBalanceFraction: 0.5,
            reserveBalance: 10,
            cashInMinScore: 36,
            finalDump: true,
            minBid: 1,
            endgameMultiplier: 2.4,
            finalAuctionMultiplier: 0,
            qPenalty: 0.42,
            synergyMultiplier: 2.25,
          },
        },
        {
          name: "generated-q-averse",
          config: {
            bidMultiplier: 1.35,
            firstPriceShade: 0.58,
            maxBidBalanceFraction: 0.36,
            reserveBalance: 20,
            cashInMinScore: 34,
            finalDump: true,
            minBid: 1,
            endgameMultiplier: 2.1,
            finalAuctionMultiplier: 0,
            qPenalty: 0.14,
            synergyMultiplier: 1.1,
          },
        },
        {
          name: "generated-word-greedy",
          config: {
            bidMultiplier: 1.85,
            firstPriceShade: 0.74,
            maxBidBalanceFraction: 0.58,
            reserveBalance: 6,
            cashInMinScore: 18,
            finalDump: true,
            minBid: 1,
            endgameMultiplier: 1.7,
            finalAuctionMultiplier: 0,
            qPenalty: 0.78,
            synergyMultiplier: 1.55,
          },
        },
        {
          name: "generated-auction-shader",
          config: {
            bidMultiplier: 1.65,
            firstPriceShade: 0.38,
            maxBidBalanceFraction: 0.48,
            reserveBalance: 14,
            cashInMinScore: 46,
            finalDump: true,
            minBid: 1,
            endgameMultiplier: 3.2,
            finalAuctionMultiplier: 0.04,
            qPenalty: 0.6,
            synergyMultiplier: 1.3,
          },
        },
      ],
    },
    ranges: {
      bidMultiplier: [0.6, 2.8],
      firstPriceShade: [0.35, 0.95],
      maxBidBalanceFraction: [0.1, 0.85],
      reserveBalance: [0, 45],
      cashInMinScore: [12, 80],
      minBid: [0, 6],
      endgameMultiplier: [0.8, 6],
      finalAuctionMultiplier: [0, 0.2],
      qPenalty: [0.1, 1.1],
      synergyMultiplier: [0.8, 2.5],
    } as Record<string, readonly [number, number]>,
    grid: {
      bidMultipliers: [0.9, 1.2, 1.5, 1.9, 2.3],
      maxBidBalanceFractions: [0.2, 0.35, 0.5, 0.65],
      reserveBalances: [0, 8, 16, 28],
      endgameMultipliers: [1.2, 2.2, 3.5, 5],
      finalAuctionMultipliers: [0, 0.02, 0.06],
    },
    evolution: {
      eliteFraction: 0.2,
      minimumElites: 2,
      peerOpponentCount: 2,
      mutationScales: {
        bidMultiplier: 0.25,
        firstPriceShade: 0.08,
        maxBidBalanceFraction: 0.08,
        reserveBalance: 8,
        cashInMinScore: 10,
        minBid: 1,
        endgameMultiplier: 0.65,
        finalAuctionMultiplier: 0.04,
        qPenalty: 0.15,
        synergyMultiplier: 0.25,
      } as Record<string, number>,
      fitnessScoreWeight: 1,
      fitnessWinRateWeight: 120,
      fitnessRankPenalty: 35,
    },
    random: {
      mulberryIncrement: 0x6d2b79f5,
      firstShift: 15,
      firstMultiplierBase: 1,
      secondShift: 7,
      secondMultiplierBase: 61,
      finalShift: 14,
      uint32Divisor: 4294967296,
    },
    worker: {
      kindEvaluate: "evaluate",
      importMetaUrl: import.meta.url,
    },
    output: {
      jsonIndent: 2,
      topCount: 10,
      compareCount: 2,
      generationTopCount: 5,
      generationFilePad: 4,
      generationFilePrefix: "generation-",
      generationFileExtension: ".json",
    },
    test: {
      importTimeoutMs: 2000,
      quizScore: 33,
      playerOne: 1,
      playerTwo: 2,
      playerThree: 3,
      tieBid: 7,
      lowerBid: 5,
      firstSequence: 1,
      secondSequence: 2,
      thirdSequence: 3,
      twoPlayers: 2,
      sixPlayers: 6,
      eightPlayers: 8,
      twoPlayerAuctionableTiles: 88,
      sixPlayerAuctionableTiles: 68,
      eightPlayerAuctionableTiles: 58,
      forceBidMultiplier: 50,
      unreachableCashInScore: 999,
      seed: 10,
      finalTileBag: ["Q", "U", "I", "A", "B", "C", "D", "E", "A", "B", "Z"],
    },
  },
} as const;
