// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  BotStrategy,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  teamId: __t.u64().name("team_id"),
  isSimulated: __t.bool().name("is_simulated"),
  get strategy() {
    return BotStrategy;
  },
  createdAt: __t.timestamp().name("created_at"),
});
