// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TeamRole,
} from "./types";


export default __t.row({
  teamId: __t.u64().name("team_id"),
  teamName: __t.string().name("team_name"),
  botId: __t.u64().name("bot_id"),
  botName: __t.string().name("bot_name"),
  get role() {
    return TeamRole;
  },
  credentialCount: __t.u32().name("credential_count"),
});
