// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AuctionType,
  MatchStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  get status() {
    return MatchStatus;
  },
  currentRound: __t.u32().name("current_round"),
  currentAuctionId: __t.option(__t.u64()).name("current_auction_id"),
  bagTotal: __t.u32().name("bag_total"),
  get auctionType() {
    return AuctionType.name("auction_type");
  },
  createdAt: __t.timestamp().name("created_at"),
  startedAt: __t.option(__t.timestamp()).name("started_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
});
