// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AuctionType,
  TournamentStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  get status() {
    return TournamentStatus;
  },
  swissRoundsTotal: __t.u32().name("swiss_rounds_total"),
  currentRound: __t.u32().name("current_round"),
  topCut: __t.u32().name("top_cut"),
  matchSize: __t.u32().name("match_size"),
  get auctionType() {
    return AuctionType.name("auction_type");
  },
  createdAt: __t.timestamp().name("created_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
});
