// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TournamentPhase,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  tournamentId: __t.u64().name("tournament_id"),
  matchId: __t.u64().name("match_id"),
  round: __t.u32(),
  get phase() {
    return TournamentPhase;
  },
});
